apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: {{ printf "%v-%v-%v" .Values.machineset.infrastructure_id .Values.machineset.role .Values.machineset.zone }}
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: {{ .Values.machineset.infrastructure_id }}
spec:
  replicas: 0
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: {{ .Values.machineset.infrastructure_id }}
      machine.openshift.io/cluster-api-machineset: {{ printf "%v-%v-%v" .Values.machineset.infrastructure_id .Values.machineset.role .Values.machineset.zone }}
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: {{ .Values.machineset.infrastructure_id }}
        machine.openshift.io/cluster-api-machine-role: {{ .Values.machineset.role }}
        machine.openshift.io/cluster-api-machine-type: {{ .Values.machineset.role }}
        machine.openshift.io/cluster-api-machineset: {{ printf "%v-%v-%v" .Values.machineset.infrastructure_id .Values.machineset.role .Values.machineset.zone }}
    spec:
      metadata:
        labels:
          {{ printf "node-role.kubernetes.io/%v: ''" .Values.machineset.role }}
      providerSpec:
        value:
          userDataSecret:
            name: worker-user-data
          placement:
            availabilityZone: us-west-2a
            region: us-west-2
          credentialsSecret:
            name: aws-cloud-credentials
          instanceType: m5.large
          metadata:
            creationTimestamp: null
          blockDevices:
            - ebs:
                encrypted: true
                iops: 0
                kmsKey:
                  arn: ''
                volumeSize: 120
                volumeType: gp2
          securityGroups:
            - filters:
                - name: 'tag:Name'
                  values:
                    - {{ .Values.machineset.infrastructure_id }}-worker-sg
          kind: AWSMachineProviderConfig
          tags:
            - name: kubernetes.io/cluster/{{ .Values.machineset.infrastructure_id }}
              value: owned
          deviceIndex: 0
          ami:
            id: {{ .Values.machineset.ami_id }}
          subnet:
            filters:
              - name: 'tag:Name'
                values:
                  - {{ .Values.machineset.infrastructure_id }}-private-us-west-2a
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          iamInstanceProfile:
            id: {{ .Values.machineset.infrastructure_id }}-worker-profile
